### PR TITLE
Fix multiple kubeconfigs passed in file path

### LINKED ISSUE #518: Problems when using Octant with multiple kubeconfig
Hello

This is similar to #147 but I don't think this is resolved
I have multiple kubeconfig files that I'm using through the **KUBECONFIG** env var

**What I expected?**

- By default, running octant with no params will auto select the active context from the merged KUBECONFIG env var
- Using octant with --kubeconfig param will work regardless of the KUBECONFIG current values

**What actually happened?**

The behaviour isn't consistent and I couldn't pin-point the exact time when this happens. See my try-and-error below (i renamed the yamls for readability)

```console
# setting KUBECONFIG to a single file, cluster-a
─ KUBECONFIG=/Users/omerbarel/.kube/cluster-a.yaml

# running octant works as expected
─ octant
2020-01-06T10:33:59.303+0200	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "overview/serviceEditor", "module-name": "overview"}
2020-01-06T10:33:59.309+0200	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "deployment/configuration", "module-name": "overview"}
2020-01-06T10:33:59.309+0200	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "overview/containerEditor", "module-name": "overview"}
2020-01-06T10:33:59.309+0200	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "octant/deleteObject", "module-name": "configuration"}
2020-01-06T10:33:59.312+0200	INFO	dash/dash.go:370	Using embedded Octant frontend
2020-01-06T10:33:59.324+0200	INFO	dash/dash.go:349	Dashboard is available at http://127.0.0.1:7777

^C2020-01-06T10:34:25.045+0200	INFO	cluster/cluster.go:137	removing cluster client temporary directory	{"component": "cluster client"}
2020-01-06T10:34:25.046+0200	INFO	plugin/manager.go:317	shutting down plugin watcher

# running octant with the same file cluster-a via the --kubeconfig param also works:

─ octant --kubeconfig ~/.kube/cluster-a.yaml
2020-01-06T10:34:43.700+0200	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "deployment/configuration", "module-name": "overview"}
2020-01-06T10:34:43.701+0200	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "overview/containerEditor", "module-name": "overview"}
2020-01-06T10:34:43.701+0200	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "overview/serviceEditor", "module-name": "overview"}
2020-01-06T10:34:43.701+0200	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "octant/deleteObject", "module-name": "configuration"}
2020-01-06T10:34:43.701+0200	INFO	dash/dash.go:370	Using embedded Octant frontend
2020-01-06T10:34:43.714+0200	INFO	dash/dash.go:349	Dashboard is available at http://127.0.0.1:7777

^C2020-01-06T10:34:55.478+0200	INFO	cluster/cluster.go:137	removing cluster client temporary directory	{"component": "cluster client"}

# setting KUBECONFIG to a single file, cluster-b

─ KUBECONFIG=/Users/omerbarel/.kube/cluster-b.yaml

# running octant works as expected

─ octant
2020-01-06T10:35:17.162+0200	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "overview/serviceEditor", "module-name": "overview"}
2020-01-06T10:35:17.162+0200	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "deployment/configuration", "module-name": "overview"}
2020-01-06T10:35:17.162+0200	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "overview/containerEditor", "module-name": "overview"}
2020-01-06T10:35:17.162+0200	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "octant/deleteObject", "module-name": "configuration"}
2020-01-06T10:35:17.165+0200	INFO	dash/dash.go:370	Using embedded Octant frontend
2020-01-06T10:35:17.173+0200	INFO	dash/dash.go:349	Dashboard is available at http://127.0.0.1:7777

^C2020-01-06T10:35:31.973+0200	INFO	plugin/manager.go:317	shutting down plugin watcher
2020-01-06T10:35:31.973+0200	INFO	cluster/cluster.go:137	removing cluster client temporary directory	{"component": "cluster client"}

# running octant with the same file cluster-b via the --kubeconfig param also works:

─ octant --kubeconfig ~/.kube/cluster-b.yaml
2020-01-06T10:35:52.655+0200	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "overview/serviceEditor", "module-name": "overview"}
2020-01-06T10:35:52.656+0200	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "deployment/configuration", "module-name": "overview"}
2020-01-06T10:35:52.656+0200	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "overview/containerEditor", "module-name": "overview"}
2020-01-06T10:35:52.656+0200	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "octant/deleteObject", "module-name": "configuration"}
2020-01-06T10:35:52.656+0200	INFO	dash/dash.go:370	Using embedded Octant frontend
2020-01-06T10:35:52.665+0200	INFO	dash/dash.go:349	Dashboard is available at http://127.0.0.1:7777

^C2020-01-06T10:36:04.753+0200	INFO	cluster/cluster.go:137	removing cluster client temporary directory	{"component": "cluster client"}

# KUBECONFIG is still set to cluster-b
# passing cluster-a as parameter value, also works:

─ octant --kubeconfig ~/.kube/cluster-a.yaml
2020-01-06T10:36:18.340+0200	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "deployment/configuration", "module-name": "overview"}
2020-01-06T10:36:18.341+0200	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "overview/containerEditor", "module-name": "overview"}
2020-01-06T10:36:18.341+0200	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "overview/serviceEditor", "module-name": "overview"}
2020-01-06T10:36:18.341+0200	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "octant/deleteObject", "module-name": "configuration"}
2020-01-06T10:36:18.342+0200	INFO	dash/dash.go:370	Using embedded Octant frontend
2020-01-06T10:36:18.349+0200	INFO	dash/dash.go:349	Dashboard is available at http://127.0.0.1:7777

^C2020-01-06T10:36:26.929+0200	INFO	cluster/cluster.go:137	removing cluster client temporary directory	{"component": "cluster client"}
2020-01-06T10:36:26.930+0200	INFO	plugin/manager.go:317	shutting down plugin watcher

# creating a merged KUBECONFIG env:

KUBECONFIG=/Users/omerbarel/.kube/cluster-b.yaml:/Users/omerbarel/.kube/cluster-a.yaml

# running octant still works, cluster b was selected automatically:

─ kubectx
cluster-a
*cluster-b*

─ octant
2020-01-06T10:37:01.740+0200	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "deployment/configuration", "module-name": "overview"}
2020-01-06T10:37:01.741+0200	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "overview/containerEditor", "module-name": "overview"}
2020-01-06T10:37:01.741+0200	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "overview/serviceEditor", "module-name": "overview"}
2020-01-06T10:37:01.741+0200	INFO	module/manager.go:79	registering action	{"component": "module-manager", "actionPath": "octant/deleteObject", "module-name": "configuration"}
2020-01-06T10:37:01.743+0200	INFO	dash/dash.go:370	Using embedded Octant frontend
2020-01-06T10:37:01.752+0200	INFO	dash/dash.go:349	Dashboard is available at http://127.0.0.1:7777

^C2020-01-06T10:37:07.408+0200	INFO	cluster/cluster.go:137	removing cluster client temporary directory	{"component": "cluster client"}
2020-01-06T10:37:07.408+0200	INFO	plugin/manager.go:317	shutting down plugin watcher

# switching context

─ kubectx cluster-a
Switched to context "cluster-a.

# running octant fails

─ octant
2020-01-06T10:37:15.157+0200	ERROR	commands/dash.go:96	dashboard failed	{"err": "failed to init cluster client: invalid configuration: [context was not found for specified context: cluster-a, cluster has no server defined]"}
github.com/vmware-tanzu/octant/internal/commands.newOctantCmd.func1.2
	/private/tmp/octant-20191108-95744-1plrk02/src/github.com/vmware-tanzu/octant/internal/commands/dash.go:96
```

### LINKED ISSUE #909: Context popup window is too narrow for longer contextes
Currently if you have a long context (see attachment) it's truncated and there is now way to determine which one is it without clicking and selecting it. 

Ideally popup should be resized to accommodate longer contexts or have a tooltip coming on hovering (similar to img alt)

**Environment:**
- Octant version (use `octant version`): 
```
Version:  0.12.1
Git commit:  870ee5775b84981ecc8f01e9a90f5182972c56bf
Built:  2020-04-24T10:27:13Z
```
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

image

### PR DESCRIPTION
**Pull request by GuessWhoSamFoo**
**What this PR does / why we need it**:
`os.Stat` would be passed a string of file paths separated by a color and would not be returning the correct error. This PR will check for the existence of each kube config (although the watcher will fail and octant will not start if any of them do not exist).

**Which issue(s) this PR fixes**
- Partially fixes #518

### CODE REVIEW

File: pkg/dash/dash.go [hunk 1]
```diff
@@ -544,8 +545,19 @@ func enableOpenCensus() error {
 
 // findKubeConfig looks for kube config from .kube or provided by user
 func findKubeConfig(logger log.Logger, kubeConfig string) error {
-	if _, err := os.Stat(kubeConfig); err == nil {
-		logger.Infof("using kube config: %v", kubeConfig)
+	found := false
+	paths := filepath.SplitList(kubeConfig)
+
+	for _, path := range paths {
```
Comment (wwitzel3) [inline pkg/dash/dash.go:551]: I would prefer to see this loop running and capturing the error for each kubeconfig passed in.
We can then exclude any configs we are unable to stat from the Watch and log the paths we failed to stat as errors.

Also, the comment in the PR reads that we will fail if any of the kubeconfig passed in are inaccessible. I don't think that is the behavior this code has, but also I think that is wrong behavior here, we can provide a good message around this. Consider something like:

```
Watching kubeconfig:
  - /path/to/config [SUCCESS]
  - /path/to/config [SUCCESS]
  - /path/to/config [FAILED]
```

Comment (GuessWhoSamFoo) [reply pkg/dash/dash.go:551]: The failure happens later when creating a cluster client with the bad config path. If we want the behavior for octant to run if any of the provided paths are valid, `findKubeConfig` will have to return a filtered file list

Comment (wwitzel3) [reply pkg/dash/dash.go:551]: I don't think we should add the path when `os.Stat` fails.

Comment (GuessWhoSamFoo) [reply pkg/dash/dash.go:552]: The watcher already shows what is being watched.
```
2020-07-29T09:50:50.811-0700    INFO    dash/watcher.go:116     watching config file    {"component": "config-watcher", "config": "/home/sfoo/.kube/config"}
2020-07-29T09:50:50.811-0700    INFO    dash/watcher.go:116     watching config file    {"component": "config-watcher", "config": "/home/sfoo/.kube/octant-dev-cluster"}
```
Instead logging will only show what can't be found

File: pkg/dash/dash.go [hunk 2]
```diff
@@ -542,13 +544,23 @@ func enableOpenCensus() error {
 	return nil
 }
 
-// findKubeConfig looks for kube config from .kube or provided by user
-func findKubeConfig(logger log.Logger, kubeConfig string) error {
-	if _, err := os.Stat(kubeConfig); err == nil {
-		logger.Infof("using kube config: %v", kubeConfig)
-		return nil
+// validateKubeConfig returns a valid file list of kube config(s)
+func validateKubeConfig(logger log.Logger, kubeConfig string) (string, error) {
```
Comment (wwitzel3) [inline pkg/dash/dash.go:548]: Let's add a basic test for this method, should be easy to verify the behavior of using a bad path and a good path.

Comment (GuessWhoSamFoo) [reply pkg/dash/dash.go]: Switched to afero instead of `os.Stat` for testing purposes
