### PR TITLE
Remove boolean value from object store Get

### LINKED ISSUE #540: grpc: server failed to encode response
My plugin is generating the following error message in the console the first time that the user navigates to the plugin in the UI when the `Get` function in the dashboard client is executed:

`grpc: server failed to encode response:  rpc error: code = Internal desc = grpc: error while marshaling: proto: Marshal called with nil`

and after the first time navigating there, every invocation of the function works flawlessly. To reproduce the error:

1. modify the sample plugin in the octant source code, so that its handleNavigation and initRoutes functions (in main.go) are replaced with:

```
func handleNavigation(request *service.NavigationRequest) (navigation.Navigation, error) {
        return navigation.Navigation{
                Title:    "Sample Plugin",
                Path:     request.GeneratePath(),
                IconName: "cloud",
        }, nil
}

func initRoutes(router *service.Router) {
        router.HandleFunc("*", func(request *service.Request) (component.ContentResponse, error) {
                contentResponse := component.NewContentResponse(component.TitleFromString("Example"))

                ctx := request.Context()
                client := request.DashboardClient()
                key := store.Key{APIVersion: "apps/v1", Kind: "Deployment", Namespace: "argo", Name: "argo-ui"}

                _, _, err := client.Get(ctx, key)
                if err != nil {
                        contentResponse.Add(component.NewText("Failed"))
                } else {
                        contentResponse.Add(component.NewText("Success"))
                }
                return *contentResponse, nil
        })
}
```
2. Install argo with the two commands listed at https://github.com/argoproj/argo . (This is needed since the `Get` is trying to fetch the argo deployment)
3. Compile octant, install the plugin, and Launch octant
4. When you navigate to the Sample plugin you will see the error in the console. "Success" is displayed in the UI, indicating that things are fine. Navigate around and notice that the console error does not appear again.

### PR DESCRIPTION
**Pull request by GuessWhoSamFoo**
**What this PR does / why we need it**:
This PR removes the found boolean from Get because both an invalid key or non-existent object will return a nil object. The value is redundant and potentially misleading because Get uses the dynamic informer as a fallback.

This also fixes the case where a Get returns nil and prevents encoding of a nil object.

**Which issue(s) this PR fixes**
- Fixes #540

**Special notes for your reviewer**: This is a breaking API change :warning:

Signed-off-by: GuessWhoSamFoo <foos@vmware.com>

### CODE REVIEW

File: internal/objectstore/dynamic_cache.go [hunk 1]
```diff
@@ -341,16 +341,19 @@ func (dc *DynamicCache) Get(ctx context.Context, key store.Key) (*unstructured.U
...
 		if kerrors.IsNotFound(err) {
-			return nil, false, nil
+			return nil, nil
 		}
 
-		return nil, false, err
+		return nil, err
+	}
+
+	if object == nil {
```
Comment (wwitzel3) [inline internal/objectstore/dynamic_cache.go]: I don't think this is needed?

File: pkg/plugin/api/client.go [hunk 2]
```diff
@@ -100,25 +100,25 @@ func (c *Client) List(ctx context.Context, key store.Key) (*unstructured.Unstruc
 }
 
 // Get retrieves an object from the dashboard's objectStore.
-func (c *Client) Get(ctx context.Context, key store.Key) (*unstructured.Unstructured, bool, error) {
+func (c *Client) Get(ctx context.Context, key store.Key) (*unstructured.Unstructured, error) {
```
Comment (wwitzel3) [inline pkg/plugin/api/client.go]: I'm still thinking about this. We can make this entire change, fix the bug, but still keep the API for Plugin Get the same. Providing a `found` helper value.

Internally, I think it makes sense, since as you mentioned, we are using the dynamic client, but for the plugins, does it make sense to keep the `found` value? What do you think?

Comment (GuessWhoSamFoo) [reply pkg/plugin/api/client.go]: An edge case where the object is nil while found is true is if there is a layer for validating keys. In other words, a found helper can be used to communicate to plugin authors that a given key will always return a nil object. Opened #655 to implement if we reach a consensus on this.

**Review by wwitzel3 — APPROVED** [review]

File: internal/objectstore/dynamic_cache.go (hunk 1 above)
Comment (wwitzel3) [reply internal/objectstore/dynamic_cache.go]: @GuessWhoSamFoo I think 352 - 354 can be deleted?

Comment (wwitzel3) [inline internal/objectstore/dynamic_cache.go]: remove 352-354

**Review by wwitzel3 — CHANGES_REQUESTED** [review]
1 minor thing and then LGTM

**Review by wwitzel3 — APPROVED** [review]
