### PR TITLE
fix container logs when the log lines are not timestamped

### LINKED ISSUE #649: Octant not showing logs for pods running on Virtual Node
**What steps did you take and what happened:**
I am running a Kubernetes cluster on Azure Kubernetes Service (AKS) with Virtual Nodes enabled. The Kubernetes control plane of AKS shows the logs associated with pods which are scheduled on the physical nodes as well as the virtual nodes of the cluster. Octant is unable to show the logs for the same pods which are scheduled and running successfully on both physical as well as virtual nodes.

Please refer to the attached images for more details

**What did you expect to happen:**
My expectation is that under the logs section for each pod, Octant shows the logs correctly. 

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**
Octant version : 0.9.1
Kubectl Client version 1.17.1
Kubectl server version : 1.14.8
OS : Windows 10

k8s virtual node logs
K8s virtual node pods
octant virtual node logs

- Octant version (use `octant version`): 
- Kubernetes version (use `kubectl version`):
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc):

### LINKED ISSUE #729: no logs
**What steps did you take and what happened:**
Clicked on logs tab to view logs however, I only see "No logs"
When viewing the same pod with kubectl logs -f I can see logs
I've tried ticking and unticking "Display timestamp" with no luck

**What did you expect to happen:**
To view logs

**Anything else you would like to add:**
logs from octant
2020-02-25T12:02:10.308Z        INFO    api/api.go:99   unable to serve {"code": 500, "message": "check if container has started: get pod serene-web-5b76858fcf-cb8rd in serene-dev: pods \"serene-web-5b76858fcf-cb8rd\" not found"}
W0225 12:02:11.088859   10764 reflector.go:302] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: watch of *unstructured.Unstructured ended with: too old resource version: 100771155 (100773780)

states the pod can't be found which is not valid.

S C:\Users\abx> kb get pod serene-web-5b76858fcf-cb8rd -n serene-dev
NAME                          READY   STATUS    RESTARTS   AGE
serene-web-5b76858fcf-cb8rd   1/1     Running   0          4d23h

**Environment:**

- Octant version (use `octant version`): 0.10.2
- Kubernetes version (use `kubectl version`): 1.17.1
- OS (macOS 10.15, Windows 10, Ubuntu 19.10 etc): Windows 10

### PR DESCRIPTION
**Pull request by wwitzel3**
Signed-off-by: Wayne Witzel III <wayne@riotousliving.com>

**What this PR does / why we need it**:
AKS VirtualNode containers (maybe others?) log entries are not timestamped. This caused our timestamp parsing to result in an error and hide log lines.

**Which issue(s) this PR fixes**
- Fixes #649
- Fixes #729

### CODE REVIEW

**Comment by wwitzel3** [comment]
@vmware-tanzu/octant-reviewers PTAL

File: internal/modules/overview/logviewer/logviewer.go [hunk 1]
```diff
@@ -47,6 +47,10 @@ func ToComponent(object runtime.Object) (component.Component, error) {
 		containerNames = append(containerNames, c.Name)
 	}
 
+	for _, c := range pod.Spec.EphemeralContainers {
+		containerNames = append(containerNames, c.Name)
```
Comment (GuessWhoSamFoo) [inline internal/modules/overview/logviewer/logviewer.go]: It can be handled in a separate PR, but the debugger container should be shown in the summary view.

**Review by GuessWhoSamFoo — APPROVED** [review]
