### PR TITLE
Log a warning when the external metrics server is offline

### LINKED ISSUE #1023: Applications page fails to render if an apiservice is not available
**What steps did you take and what happened:**

When navigating to the "Applications" tab in the nav bar, the UI switches to a throbber and re-renders the previous page. 

**What did you expect to happen:**

I expected to see the Applications overview page.

**Anything else you would like to add:**

```
2020-06-29T10:48:28.637-0400    ERROR   api/content_manager.go:130      generate content       {"client-id": "54a08fe0-ba0d-11ea-a290-8c859082b335", "err": "generate content: load cards cards: collect workload cards: load workloads: get metrics for pod 'test-deployment-5d5464955c-hncb6': check for pod metrics support: get preferred namespaced resources: unable to retrieve the complete list of server APIs: external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request", "content-path": "workloads/namespace/default"}
github.com/vmware-tanzu/octant/internal/api.(*ContentManager).runUpdate.func1
        /Users/scothis/Development/vmware-tanzu/octant/internal/api/content_manager.go:130
github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run.func1
        /Users/scothis/Development/vmware-tanzu/octant/internal/api/poller.go:86
github.com/vmware-tanzu/octant/internal/api.(*InterruptiblePoller).Run
        /Users/scothis/Development/vmware-tanzu/octant/internal/api/poller.go:95
github.com/vmware-tanzu/octant/internal/api.(*ContentManager).Start
        /Users/scothis/Development/vmware-tanzu/octant/internal/api/content_manager.go:106
```

**Environment:**

- HEAD

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.4", GitCommit:"c96aede7b5205121079932896c4ad89bb93260af", GitTreeState:"clean", BuildDate:"2020-06-18T02:59:13Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.8-gke.15", GitCommit:"9cabee15e0922c3b36724de4866a98f6c2da5e6a", GitTreeState:"clean", BuildDate:"2020-05-01T21:47:04Z", GoVersion:"go1.13.8b4", Compiler:"gc", Platform:"linux/amd64"}
```

```
$ kubectl get apiservices
NAME                                        SERVICE                      AVAILABLE                 AGE
v1.                                         Local                        True                      93d
v1.admissionregistration.k8s.io             Local                        True                      30d
v1.apiextensions.k8s.io                     Local                        True                      30d
v1.apps                                     Local                        True                      93d
v1.authentication.k8s.io                    Local                        True                      93d
v1.authorization.k8s.io                     Local                        True                      93d
v1.autoscaling                              Local                        True                      93d
v1.batch                                    Local                        True                      93d
<snip>
v1beta1.external.metrics.k8s.io             keda/keda-operator           False (ServiceNotFound)   93d
<snip>
```

### PR DESCRIPTION
**Pull request by wwitzel3**
Signed-off-by: Wayne Witzel III <wayne@riotousliving.com>

**Which issue(s) this PR fixes**
- Fixes #1023

### CODE REVIEW

File: internal/octant/workload.go [hunk 1]
```diff
@@ -639,3 +645,13 @@ func CreateWorkloadSummary(workload *Workload, summarySize component.DonutChartS
 		MetricsEnabled: true,
 	}, nil
 }
+
+func ExternalMetricsUnavailable(e error) bool {
```
Comment (GuessWhoSamFoo) [inline internal/octant/workload.go:649]: Instead of parsing out strings from the error, we can try to catch the error in https://github.com/vmware-tanzu/octant/blob/master/internal/octant/pod_metrics_loader.go#L158 by using `discovery.IsGroupDiscoveryFailedError` to identify instead since `ExternalMetricsUnavailable` and `IsPodMetricsNotSupported` are really the same here.

**Review by GuessWhoSamFoo — APPROVED** [review]
